name: Build and Push Docker Image

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: 'Development'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          touch .env
          echo "NEXT_PUBLIC_WEB3AUTH_NETWORK=${{ vars.NEXT_PUBLIC_WEB3AUTH_NETWORK }}" >> .env
          echo "NEXT_PUBLIC_WEB3AUTH_CLIENT_ID=${{ secrets.NEXT_PUBLIC_WEB3AUTH_CLIENT_ID }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_RPC_TARGET=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_RPC_TARGET }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_CHAIN_NAMESPACE=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_CHAIN_NAMESPACE }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_DISPLAY_NAME=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_DISPLAY_NAME }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_CHAIN_ID=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_CHAIN_ID }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_ADDRESS_PREFIX=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_ADDRESS_PREFIX }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_DENOM=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_DENOM }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_URL_SCHEME=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_URL_SCHEME }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_URL_DOMAIN=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_URL_DOMAIN }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_GAS_PRICE=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_GAS_PRICE }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_GAS_LIMIT_MULTIPLIER=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_GAS_LIMIT_MULTIPLIER }}" >> .env

          cat .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: lifted/ghostcloud-frontend:latest
